//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using Tobasco.CodeGeneration.Model.Xml.Enums;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://TobascoCore/EntitySchema.xsd", IsNullable = false)]
public partial class Entity
{

    private EntityEntityLocation entityLocationField;

    private EntityDatabase databaseField;

    private EntityProperty[] propertiesField;

    private string nameField;

    /// <remarks/>
    public EntityEntityLocation EntityLocation
    {
        get
        {
            return this.entityLocationField;
        }
        set
        {
            this.entityLocationField = value;
        }
    }

    /// <remarks/>
    public EntityDatabase Database
    {
        get
        {
            return this.databaseField;
        }
        set
        {
            this.databaseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable = false)]
    public EntityProperty[] Properties
    {
        get
        {
            return this.propertiesField;
        }
        set
        {
            this.propertiesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityEntityLocation
{

    private EntityEntityLocationFileLocation fileLocationField;

    private EntityEntityLocationNamespaces namespacesField;

    private EntityEntityLocationBaseClass baseClassField;

    private bool generaterulesField;

    private bool generaterulesFieldSpecified;

    private string idField;

    private string overrideKeyField;

    /// <remarks/>
    public EntityEntityLocationFileLocation FileLocation
    {
        get
        {
            return this.fileLocationField;
        }
        set
        {
            this.fileLocationField = value;
        }
    }

    /// <remarks/>
    public EntityEntityLocationNamespaces Namespaces
    {
        get
        {
            return this.namespacesField;
        }
        set
        {
            this.namespacesField = value;
        }
    }

    /// <remarks/>
    public EntityEntityLocationBaseClass BaseClass
    {
        get
        {
            return this.baseClassField;
        }
        set
        {
            this.baseClassField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generaterules
    {
        get
        {
            return this.generaterulesField;
        }
        set
        {
            this.generaterulesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool generaterulesSpecified
    {
        get
        {
            return this.generaterulesFieldSpecified;
        }
        set
        {
            this.generaterulesFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string overrideKey
    {
        get
        {
            return this.overrideKeyField;
        }
        set
        {
            this.overrideKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityEntityLocationFileLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityEntityLocationNamespaces
{

    private EntityEntityLocationNamespacesNamespace namespaceField;

    /// <remarks/>
    public EntityEntityLocationNamespacesNamespace Namespace
    {
        get
        {
            return this.namespaceField;
        }
        set
        {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityEntityLocationNamespacesNamespace
{

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityEntityLocationBaseClass
{

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityEntityLocationORMapper
{

    private string typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabase
{

    private EntityDatabaseStoredProcedures storedProceduresField;

    private EntityDatabaseTables tablesField;

    private string projectField;

    /// <remarks/>
    public EntityDatabaseStoredProcedures StoredProcedures
    {
        get
        {
            return this.storedProceduresField;
        }
        set
        {
            this.storedProceduresField = value;
        }
    }

    /// <remarks/>
    public EntityDatabaseTables Tables
    {
        get
        {
            return this.tablesField;
        }
        set
        {
            this.tablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseStoredProcedures
{

    private EntityDatabaseStoredProceduresInsert insertField;

    private EntityDatabaseStoredProceduresUpdate updateField;

    private EntityDatabaseStoredProceduresDelete deleteField;

    private EntityDatabaseStoredProceduresGetById getByIdField;

    private EntityDatabaseStoredProceduresMerge mergeField;

    private string folderField;

    private bool generateField;

    /// <remarks/>
    public EntityDatabaseStoredProceduresInsert Insert
    {
        get
        {
            return this.insertField;
        }
        set
        {
            this.insertField = value;
        }
    }

    /// <remarks/>
    public EntityDatabaseStoredProceduresUpdate Update
    {
        get
        {
            return this.updateField;
        }
        set
        {
            this.updateField = value;
        }
    }

    /// <remarks/>
    public EntityDatabaseStoredProceduresDelete Delete
    {
        get
        {
            return this.deleteField;
        }
        set
        {
            this.deleteField = value;
        }
    }

    /// <remarks/>
    public EntityDatabaseStoredProceduresGetById GetById
    {
        get
        {
            return this.getByIdField;
        }
        set
        {
            this.getByIdField = value;
        }
    }

    /// <remarks/>
    public EntityDatabaseStoredProceduresMerge Merge
    {
        get
        {
            return this.mergeField;
        }
        set
        {
            this.mergeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseStoredProceduresInsert
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseStoredProceduresUpdate
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseStoredProceduresDelete
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseStoredProceduresGetById
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseStoredProceduresMerge
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseTables
{

    private EntityDatabaseTablesHistorie historieField;

    private string folderField;

    private bool generateField;

    /// <remarks/>
    public EntityDatabaseTablesHistorie Historie
    {
        get
        {
            return this.historieField;
        }
        set
        {
            this.historieField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityDatabaseTablesHistorie
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityProperty
{

    private EntityPropertyDataType dataTypeField;

    private string nameField;

    private bool requiredField;

    /// <remarks/>
    public EntityPropertyDataType DataType
    {
        get
        {
            return this.dataTypeField;
        }
        set
        {
            this.dataTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool required
    {
        get
        {
            return this.requiredField;
        }
        set
        {
            this.requiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/EntitySchema.xsd")]
public partial class EntityPropertyDataType
{

    private string nameField;

    private byte sizeField;

    private bool sizeFieldSpecified;

    private DataType typeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sizeSpecified
    {
        get
        {
            return this.sizeFieldSpecified;
        }
        set
        {
            this.sizeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DataType type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}
