//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://TobascoCore/MainInfoSchema.xsd", IsNullable = false)]
public partial class EntityInformation
{

    private EntityInformationEntityLocation entityLocationField;

    private EntityInformationBaseNamespaces baseNamespacesField;

    private EntityInformationEnumNamespace enumNamespaceField;

    private EntityInformationDatabase databaseField;

    private EntityInformationDescription descriptionField;

    private EntityInformationRepository repositoryField;

    private EntityInformationDependencyInjection dependencyInjectionField;

    private EntityInformationConnectionFactory connectionFactoryField;

    private EntityInformationGenericRepository genericRepositoryField;

    /// <remarks/>
    public EntityInformationEntityLocation EntityLocation
    {
        get
        {
            return this.entityLocationField;
        }
        set
        {
            this.entityLocationField = value;
        }
    }

    /// <remarks/>
    public EntityInformationBaseNamespaces BaseNamespaces
    {
        get
        {
            return this.baseNamespacesField;
        }
        set
        {
            this.baseNamespacesField = value;
        }
    }

    /// <remarks/>
    public EntityInformationEnumNamespace EnumNamespace
    {
        get
        {
            return this.enumNamespaceField;
        }
        set
        {
            this.enumNamespaceField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDatabase Database
    {
        get
        {
            return this.databaseField;
        }
        set
        {
            this.databaseField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDescription Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public EntityInformationRepository Repository
    {
        get
        {
            return this.repositoryField;
        }
        set
        {
            this.repositoryField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDependencyInjection DependencyInjection
    {
        get
        {
            return this.dependencyInjectionField;
        }
        set
        {
            this.dependencyInjectionField = value;
        }
    }

    /// <remarks/>
    public EntityInformationConnectionFactory ConnectionFactory
    {
        get
        {
            return this.connectionFactoryField;
        }
        set
        {
            this.connectionFactoryField = value;
        }
    }

    /// <remarks/>
    public EntityInformationGenericRepository GenericRepository
    {
        get
        {
            return this.genericRepositoryField;
        }
        set
        {
            this.genericRepositoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationEntityLocation
{

    private EntityInformationEntityLocationFileLocation fileLocationField;

    private EntityInformationEntityLocationNamespaces namespacesField;

    private string idField;

    private bool generaterulesField;

    private bool generaterulesFieldSpecified;

    /// <remarks/>
    public EntityInformationEntityLocationFileLocation FileLocation
    {
        get
        {
            return this.fileLocationField;
        }
        set
        {
            this.fileLocationField = value;
        }
    }

    /// <remarks/>
    public EntityInformationEntityLocationNamespaces Namespaces
    {
        get
        {
            return this.namespacesField;
        }
        set
        {
            this.namespacesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generaterules
    {
        get
        {
            return this.generaterulesField;
        }
        set
        {
            this.generaterulesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool generaterulesSpecified
    {
        get
        {
            return this.generaterulesFieldSpecified;
        }
        set
        {
            this.generaterulesFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationEntityLocationFileLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationEntityLocationNamespaces
{

    private EntityInformationEntityLocationNamespacesNamespace namespaceField;

    /// <remarks/>
    public EntityInformationEntityLocationNamespacesNamespace Namespace
    {
        get
        {
            return this.namespaceField;
        }
        set
        {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationEntityLocationNamespacesNamespace
{

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationBaseNamespaces
{

    private EntityInformationBaseNamespacesNamespace namespaceField;

    /// <remarks/>
    public EntityInformationBaseNamespacesNamespace Namespace
    {
        get
        {
            return this.namespaceField;
        }
        set
        {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationBaseNamespacesNamespace
{

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationEnumNamespace
{

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationMappers
{

    private EntityInformationMappersMapper[] mapperField;

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mapper")]
    public EntityInformationMappersMapper[] Mapper
    {
        get
        {
            return this.mapperField;
        }
        set
        {
            this.mapperField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationMappersMapper
{

    private EntityInformationMappersMapperMapperLocation mapperLocationField;

    private EntityInformationMappersMapperInterfaceLocation interfaceLocationField;

    private EntityInformationMappersMapperFromTo fromToField;

    /// <remarks/>
    public EntityInformationMappersMapperMapperLocation MapperLocation
    {
        get
        {
            return this.mapperLocationField;
        }
        set
        {
            this.mapperLocationField = value;
        }
    }

    /// <remarks/>
    public EntityInformationMappersMapperInterfaceLocation InterfaceLocation
    {
        get
        {
            return this.interfaceLocationField;
        }
        set
        {
            this.interfaceLocationField = value;
        }
    }

    /// <remarks/>
    public EntityInformationMappersMapperFromTo FromTo
    {
        get
        {
            return this.fromToField;
        }
        set
        {
            this.fromToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationMappersMapperMapperLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationMappersMapperInterfaceLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationMappersMapperFromTo
{

    private string fromField;

    private string toField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string from
    {
        get
        {
            return this.fromField;
        }
        set
        {
            this.fromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to
    {
        get
        {
            return this.toField;
        }
        set
        {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabase
{

    private EntityInformationDatabaseStoredProcedures storedProceduresField;

    private EntityInformationDatabaseTables tablesField;

    private string projectField;

    /// <remarks/>
    public EntityInformationDatabaseStoredProcedures StoredProcedures
    {
        get
        {
            return this.storedProceduresField;
        }
        set
        {
            this.storedProceduresField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDatabaseTables Tables
    {
        get
        {
            return this.tablesField;
        }
        set
        {
            this.tablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseStoredProcedures
{

    private EntityInformationDatabaseStoredProceduresInsert insertField;

    private EntityInformationDatabaseStoredProceduresUpdate updateField;

    private EntityInformationDatabaseStoredProceduresDelete deleteField;

    private EntityInformationDatabaseStoredProceduresGetById getByIdField;

    private EntityInformationDatabaseStoredProceduresMerge mergeField;

    private string folderField;

    private bool generateField;

    /// <remarks/>
    public EntityInformationDatabaseStoredProceduresInsert Insert
    {
        get
        {
            return this.insertField;
        }
        set
        {
            this.insertField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDatabaseStoredProceduresUpdate Update
    {
        get
        {
            return this.updateField;
        }
        set
        {
            this.updateField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDatabaseStoredProceduresDelete Delete
    {
        get
        {
            return this.deleteField;
        }
        set
        {
            this.deleteField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDatabaseStoredProceduresGetById GetById
    {
        get
        {
            return this.getByIdField;
        }
        set
        {
            this.getByIdField = value;
        }
    }

    /// <remarks/>
    public EntityInformationDatabaseStoredProceduresMerge Merge
    {
        get
        {
            return this.mergeField;
        }
        set
        {
            this.mergeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseStoredProceduresInsert
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseStoredProceduresUpdate
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseStoredProceduresDelete
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseStoredProceduresGetById
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseStoredProceduresMerge
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseTables
{

    private EntityInformationDatabaseTablesHistorie historieField;

    private string folderField;

    private bool generateField;

    /// <remarks/>
    public EntityInformationDatabaseTablesHistorie Historie
    {
        get
        {
            return this.historieField;
        }
        set
        {
            this.historieField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDatabaseTablesHistorie
{

    private bool generateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDescription
{

    private bool requiredField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool required
    {
        get
        {
            return this.requiredField;
        }
        set
        {
            this.requiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationRepository
{

    private EntityInformationRepositoryFileLocation fileLocationField;

    private EntityInformationRepositoryTransaction transactionField;

    private EntityInformationRepositoryInterfaceLocation interfaceLocationField;

    private EntityInformationRepositoryNamespace[] namespacesField;

    private string overridekeyField;

    private string entityIdField;

    private bool generateField;

    /// <remarks/>
    public EntityInformationRepositoryFileLocation FileLocation
    {
        get
        {
            return this.fileLocationField;
        }
        set
        {
            this.fileLocationField = value;
        }
    }

    /// <remarks/>
    public EntityInformationRepositoryTransaction Transaction
    {
        get
        {
            return this.transactionField;
        }
        set
        {
            this.transactionField = value;
        }
    }

    /// <remarks/>
    public EntityInformationRepositoryInterfaceLocation InterfaceLocation
    {
        get
        {
            return this.interfaceLocationField;
        }
        set
        {
            this.interfaceLocationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Namespace", IsNullable = false)]
    public EntityInformationRepositoryNamespace[] Namespaces
    {
        get
        {
            return this.namespacesField;
        }
        set
        {
            this.namespacesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string overridekey
    {
        get
        {
            return this.overridekeyField;
        }
        set
        {
            this.overridekeyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EntityId
    {
        get
        {
            return this.entityIdField;
        }
        set
        {
            this.entityIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool generate
    {
        get
        {
            return this.generateField;
        }
        set
        {
            this.generateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationRepositoryFileLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationRepositoryTransaction
{

    private bool useTransactionField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool useTransaction
    {
        get
        {
            return this.useTransactionField;
        }
        set
        {
            this.useTransactionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationRepositoryInterfaceLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationRepositoryNamespace
{

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDependencyInjection
{

    private EntityInformationDependencyInjectionModules modulesField;

    private string typeField;

    private string overridekeyField;

    /// <remarks/>
    public EntityInformationDependencyInjectionModules Modules
    {
        get
        {
            return this.modulesField;
        }
        set
        {
            this.modulesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string overridekey
    {
        get
        {
            return this.overridekeyField;
        }
        set
        {
            this.overridekeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDependencyInjectionModules
{

    private EntityInformationDependencyInjectionModulesModule moduleField;

    /// <remarks/>
    public EntityInformationDependencyInjectionModulesModule Module
    {
        get
        {
            return this.moduleField;
        }
        set
        {
            this.moduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDependencyInjectionModulesModule
{

    private EntityInformationDependencyInjectionModulesModuleFilelocation filelocationField;

    private string nameField;

    private string typeField;

    private string scopeField;

    /// <remarks/>
    public EntityInformationDependencyInjectionModulesModuleFilelocation Filelocation
    {
        get
        {
            return this.filelocationField;
        }
        set
        {
            this.filelocationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scope
    {
        get
        {
            return this.scopeField;
        }
        set
        {
            this.scopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationDependencyInjectionModulesModuleFilelocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationConnectionFactory
{

    private EntityInformationConnectionFactoryFileLocation fileLocationField;

    private EntityInformationConnectionFactoryInterfaceLocation interfaceLocationField;

    private string overridekeyField;

    /// <remarks/>
    public EntityInformationConnectionFactoryFileLocation FileLocation
    {
        get
        {
            return this.fileLocationField;
        }
        set
        {
            this.fileLocationField = value;
        }
    }

    /// <remarks/>
    public EntityInformationConnectionFactoryInterfaceLocation InterfaceLocation
    {
        get
        {
            return this.interfaceLocationField;
        }
        set
        {
            this.interfaceLocationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string overridekey
    {
        get
        {
            return this.overridekeyField;
        }
        set
        {
            this.overridekeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationConnectionFactoryFileLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationConnectionFactoryInterfaceLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationGenericRepository
{

    private EntityInformationGenericRepositoryFileLocation fileLocationField;

    private EntityInformationGenericRepositoryInterfaceLocation interfaceLocationField;

    private string overridekeyField;

    /// <remarks/>
    public EntityInformationGenericRepositoryFileLocation FileLocation
    {
        get
        {
            return this.fileLocationField;
        }
        set
        {
            this.fileLocationField = value;
        }
    }

    /// <remarks/>
    public EntityInformationGenericRepositoryInterfaceLocation InterfaceLocation
    {
        get
        {
            return this.interfaceLocationField;
        }
        set
        {
            this.interfaceLocationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string overridekey
    {
        get
        {
            return this.overridekeyField;
        }
        set
        {
            this.overridekeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationGenericRepositoryFileLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://TobascoCore/MainInfoSchema.xsd")]
public partial class EntityInformationGenericRepositoryInterfaceLocation
{

    private string projectField;

    private string folderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string project
    {
        get
        {
            return this.projectField;
        }
        set
        {
            this.projectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folder
    {
        get
        {
            return this.folderField;
        }
        set
        {
            this.folderField = value;
        }
    }
}
